### ISSUE TITLE
Cart is not visible (error 404)

### ISSUE THREAD

**Issue by lughino** [leaphly/leaphly-sandbox#5]
Hello,
I'm trying to run the cart but I can't make it work.
When I load the page doesn't load the truck and in the console I get this error:

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://cart.local/api/v1/carts.json
```

I'm trying to find where the problem is, but I can't find it.
I followed the instructions step by step.

**Comment by liuggio** [comment]
Hi,
which page are you trying to load?
did you create the virtual host?
Which values did you set into the parameters?

**Comment by lughino** [comment]
Hi,
I'm trying to access http://cart.local
I have successfully configured virtual hosts.
I place the file parameters.yml:

```
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: 
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    leaphly_api_host: 'http://cart.local'
    leaphly_api_port: 80
```

Thank you and congratulations for the work of this bundle!
